import { useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, ArrowLeft, Check, Download, FileUp, X, Mail } from 'lucide-react';
import { companyEmail, getService, services } from './content';
import { PageIntro } from './Layout';

const fileTypes = /\.(step|stp|iges|igs|stl|obj|pdf|dwg)$/i;
export function QuotePage() {
  const [params] = useSearchParams();
  const initial = getService(params.get('process'))?.id || '';
  const [process, setProcess] = useState(initial);
  const [step, setStep] = useState(initial ? 1 : 0);
  const [files, setFiles] = useState([]);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [fields, setFields] = useState({ name: '', email: '', company: '', quantity: '', material: '', notes: '' });
  const picker = useRef();
  const selected = getService(process);
  const label = selected?.name || 'Help choosing a process';
  const update = event => setFields({ ...fields, [event.target.name]: event.target.value });
  const brief = ['RP GROUP — PROJECT BRIEF', '', `Process: ${label}`, `Name: ${fields.name}`, `Email: ${fields.email}`, `Company: ${fields.company || 'Not specified'}`, `Quantity: ${fields.quantity || 'To be confirmed'}`, `Material: ${fields.material || 'Advice requested'}`, '', 'Project notes:', fields.notes || 'Not supplied', '', 'Reference files (attach separately):', ...files.map(file => `- ${file.name}`)].join('\n');
  function addFiles(list) {
    const accepted = [], errors = [];
    for (const file of Array.from(list)) {
      if (!fileTypes.test(file.name)) errors.push(`${file.name}: use STEP, IGES, STL, OBJ, PDF or DWG.`);
      else if (file.size > 25 * 1024 * 1024) errors.push(`${file.name}: the limit is 25 MB per file.`);
      else accepted.push(file);
    }
    setFiles(previous => [...previous, ...accepted.filter(file => !previous.some(old => old.name === file.name && old.size === file.size))]);
    setError(errors.join(' '));
  }
  function download() {
    const url = URL.createObjectURL(new Blob([brief], { type: 'text/plain;charset=utf-8' }));
    const link = document.createElement('a'); link.href = url; link.download = 'rp-group-project-brief.txt'; link.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000); setNotice('Your project brief has been downloaded.');
  }
  return <><PageIntro label="START A PROJECT" title={<>Tell us what<br /><span>you’re making.</span></>} description="Choose a process, outline the requirements and prepare a project brief to share with our team." /><section className="form-shell site-width"><aside className="form-aside"><p className="eyebrow">A GOOD STARTING POINT</p><h2>A little context<br />goes a long way.</h2><p>Share what you know. If the material or process is still open, we can start with the application.</p><ol><li><Check size={15} />The part’s function</li><li><Check size={15} />Quantity and material</li><li><Check size={15} />Critical fits or dimensions</li><li><Check size={15} />A drawing or reference model</li></ol><a className="text-link" href={`mailto:${companyEmail}`}>{companyEmail} <ArrowUpRight size={14} /></a></aside><div className="project-form"><nav className="form-steps" aria-label="Project brief steps">{['Process', 'Requirements', 'Your brief'].map((title, index) => <button key={title} disabled={index > step} aria-current={index === step ? 'step' : undefined} onClick={() => { setStep(index); setNotice(''); }}><span>{index < step ? <Check size={12} /> : `0${index + 1}`}</span>{title}</button>)}</nav>
      {step === 0 && <div><p className="eyebrow">01 / THE PROCESS</p><h2>What do you have in mind?</h2><div className="process-picker">{[...services, { id: 'help', name: 'Help me choose', arm: 'group' }].map(service => <button key={service.id} aria-pressed={process === service.id} onClick={() => setProcess(service.id)}><span>{service.arm === 'rp' ? 'RP INDUSTRIES' : service.arm === 'thry' ? 'THRY CO' : 'RP GROUP'}</span><strong>{service.name}</strong><i>{process === service.id ? <Check size={14} /> : <ArrowUpRight size={14} />}</i></button>)}</div><div className="form-actions"><span>Not sure? Select “Help me choose.”</span><button className="site-button" disabled={!process} onClick={() => setStep(1)}>Continue <ArrowRight size={16} /></button></div></div>}
      {step === 1 && <form onSubmit={event => { event.preventDefault(); setStep(2); }}><p className="eyebrow">02 / {label.toUpperCase()}</p><h2>The details that matter.</h2><div className="fields-grid"><label htmlFor="quote-name">Your name *<input id="quote-name" name="name" required autoComplete="name" value={fields.name} onChange={update} placeholder="Full name" /></label><label htmlFor="quote-email">Email address *<input id="quote-email" name="email" type="email" required autoComplete="email" value={fields.email} onChange={update} placeholder="you@company.com" /></label><label htmlFor="quote-company">Company<input id="quote-company" name="company" autoComplete="organization" value={fields.company} onChange={update} placeholder="Company name" /></label><label htmlFor="quote-quantity">Quantity<input id="quote-quantity" name="quantity" type="number" min="1" step="1" value={fields.quantity} onChange={update} placeholder="Estimated number of parts" /></label><label className="field-wide" htmlFor="quote-material">Material<input id="quote-material" name="material" value={fields.material} onChange={update} placeholder="Known grade, preferred material, or ask for advice" /></label><label className="field-wide" htmlFor="quote-notes">Project notes<textarea id="quote-notes" name="notes" rows={4} value={fields.notes} onChange={update} placeholder="What does the part need to do? Include fit, finish, operating environment and timing requirements." /></label></div><div className="reference-files" onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); addFiles(event.dataTransfer.files); }}><FileUp size={25} /><div><strong>Reference drawings & models</strong><p>STEP, IGES, STL, OBJ, PDF, DWG · up to 25 MB each</p></div><button type="button" className="text-link" onClick={() => picker.current.click()}>Choose files <ArrowUpRight size={14} /></button><input ref={picker} hidden type="file" multiple accept=".step,.stp,.iges,.igs,.stl,.obj,.pdf,.dwg" onChange={event => { addFiles(event.target.files); event.target.value = ''; }} /></div><p className="field-note">Files stay on your device. Attach them when you send your project email.</p>{error && <p className="form-error" role="alert">{error}</p>}{files.length > 0 && <ul className="selected-files">{files.map((file, index) => <li key={`${file.name}-${file.size}`}><span>{file.name}</span><button type="button" aria-label={`Remove ${file.name}`} onClick={() => setFiles(files.filter((_, i) => i !== index))}><X size={14} /></button></li>)}</ul>}<div className="form-actions"><button type="button" className="text-link" onClick={() => setStep(0)}><ArrowLeft size={15} />Back</button><button className="site-button" type="submit">Review brief <ArrowRight size={16} /></button></div></form>}
      {step === 2 && <div><p className="eyebrow">03 / READY TO SHARE</p><h2>Your project, on one page.</h2><dl className="brief-summary">{[['Process', label], ['Contact', `${fields.name} · ${fields.email}`], ['Company', fields.company || 'Not specified'], ['Quantity', fields.quantity || 'To be confirmed'], ['Material', fields.material || 'Advice requested'], ['Notes', fields.notes || 'Not supplied'], ['Reference files', files.map(file => file.name).join(', ') || 'None selected']].map(([title, value]) => <div key={title}><dt>{title}</dt><dd>{value}</dd></div>)}</dl><p className="field-note">Download your brief or open it in your email app. Add the selected files as attachments before sending. Nothing has been submitted yet.</p><div className="brief-buttons"><a className="site-button" href={`mailto:${companyEmail}?subject=${encodeURIComponent(`Project enquiry — ${label}`)}&body=${encodeURIComponent(brief)}`}>Prepare email <Mail size={16} /></a><button className="site-button site-button--outline" onClick={download}>Download brief <Download size={16} /></button></div>{notice && <p className="form-notice" role="status">{notice}</p>}<button className="text-link" onClick={() => setStep(1)}><ArrowLeft size={14} />Edit requirements</button></div>}
    </div></section></>;
}

export function ContactPage() {
  const [fields, setFields] = useState({ name: '', email: '', message: '' });
  function compose(event) {
    event.preventDefault();
    const text = `Hello RP Group,\n\n${fields.message}\n\n${fields.name}\n${fields.email}`;
    window.location.href = `mailto:${companyEmail}?subject=${encodeURIComponent('RP Group enquiry')}&body=${encodeURIComponent(text)}`;
  }
  return <><PageIntro label="GET IN TOUCH" title={<>Start with<br /><span>a conversation.</span></>} description="Have a project in mind, a process question or an idea to explore? Tell us where you are starting." /><section className="form-shell site-width"><aside className="form-aside"><p className="eyebrow">DIRECT CONTACT</p><h2>Let’s find<br />the right direction.</h2><a className="contact-email" href={`mailto:${companyEmail}`}>{companyEmail}<ArrowUpRight size={20} /></a><p>For component enquiries, include the application, expected quantity and any available drawing or model.</p><div className="contact-brands"><span>RP INDUSTRIES<small>Machining · rubber · tooling</small></span><span>THRY CO<small>FDM · SLA · SLS</small></span></div></aside><form className="project-form contact-form" onSubmit={compose}><p className="eyebrow">YOUR ENQUIRY</p><h2>What can we help with?</h2>{[['name', 'Your name', 'text'], ['email', 'Email address', 'email']].map(([key, label, type]) => <label key={key} htmlFor={`contact-${key}`}>{label} *<input id={`contact-${key}`} type={type} name={key} required autoComplete={key} value={fields[key]} onChange={event => setFields({ ...fields, [key]: event.target.value })} /></label>)}<label htmlFor="contact-message">Your message *<textarea id="contact-message" required rows={5} value={fields.message} onChange={event => setFields({ ...fields, message: event.target.value })} /></label><button type="submit" className="site-button">Prepare email <ArrowUpRight size={16} /></button><p className="field-note">Opens your email app with the message prepared for you to send.</p></form></section><section className="faq-section site-width"><p className="eyebrow">A FEW USEFUL ANSWERS</p><h2>Before you get started.</h2>{[['What should I share for a quote?', 'A drawing or 3D model, material preference, quantity and key functional requirements are a useful starting point. If you are still developing the idea, explain the application.'], ['Can you help me choose a process?', 'Yes. Start with the part’s function, geometry and quantity. The process can be reviewed around those requirements.'], ['What if I only need a prototype?', 'Tell us what you want the prototype to demonstrate: appearance, fit or function. That helps focus the discussion on the right material and manufacturing approach.']].map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</section></>;
}
