import { Link, useParams } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, MoveUpRight, Check } from 'lucide-react';
import AutomotiveExperience from './AutomotiveExperience';
import { services, getService, sectors } from './content';
import { PageIntro, ProjectCTA, SectionHeading } from './Layout';
import PartPanel from './PartPanel';

function ServiceList({ arm }) { return <div className="service-list">{services.filter(s => s.arm === arm).map((s, index) => <Link key={s.id} to={s.path}><span className="service-list__number">0{index + 1}</span><div><h3>{s.name}</h3><p>{s.intro}</p></div><ArrowUpRight size={21} /></Link>)}</div>; }
function WorkflowSteps() { return <div className="workflow-steps">{[
  ['01', 'Share the idea.', 'A CAD model, drawing or brief. Tell us what the part needs to do.'],
  ['02', 'Find the process.', 'Review material, geometry, quantity and the features that matter.'],
  ['03', 'Make the next move.', 'Agree on the approach, then move from development toward production.'],
].map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div>; }

export function HomePage() { return <AutomotiveExperience />; }

export function OverviewPage({ arm }) {
  const printing = arm === 'thry';
  const featured = getService(printing ? 'sls' : 'billet');
  return <><PageIntro label={printing ? 'THRY CO / ADDITIVE MANUFACTURING' : 'AARPEE INDUSTRIES / PRECISION MANUFACTURING'} title={printing ? <>More freedom.<br /><span>In every form.</span></> : <>Built around<br /><span>the details.</span></>} description={printing ? 'Turn digital ideas into physical models. Explore form, fit and function with FDM, SLA and SLS printing.' : 'VMC machining, billet components, rubber parts, jigs and fixtures. Purposeful engineering for the assemblies you are building.'}><Link className="site-button" to={`/rfq?process=${printing ? 'fdm' : 'vmc'}`}>Discuss a component <ArrowUpRight size={17} /></Link></PageIntro><section className="overview-feature site-width"><PartPanel service={featured} /><div><p className="eyebrow">{printing ? 'BUILD THE NEXT ITERATION' : 'EVERY FEATURE HAS A FUNCTION'}</p><h2>{printing ? 'Less waiting to see your idea.' : 'The right process starts with the part.'}</h2><p>{printing ? 'A physical prototype answers questions a screen cannot. Check an interface, hold a form, assess a mechanism and refine what comes next.' : 'The geometry is only the beginning. Material, tolerance, quantity and operating conditions all influence how a component should be made.'}</p><div className="feature-checks">{(printing ? ['Compare three printing technologies', 'Explore visual and functional prototypes', 'Review geometry before manufacturing'] : ['Drawing-led process selection', 'Attention to critical interfaces', 'Components and supporting production tooling']).map(t => <span key={t}><Check size={16} />{t}</span>)}</div></div></section><section className="site-section site-width"><SectionHeading label="EXPLORE THE PROCESSES" title={printing ? 'Three ways to build.' : 'Four ways to make it work.'} /><ServiceList arm={arm} /></section><ProjectCTA /></>;
}

export function ServiceDetailPage() {
  const { serviceId } = useParams();
  const service = getService(serviceId);
  if (!service) return <NotFoundPage />;
  return <><div className="service-detail site-width"><div><Link className="breadcrumb" to={service.arm === 'rp' ? '/aarpee-industries' : '/tryco'}>← {service.arm === 'rp' ? 'AARPEE Industries' : 'Thry Co'}</Link><p className="eyebrow">{service.arm === 'rp' ? 'PRECISION MANUFACTURING' : 'ADDITIVE MANUFACTURING'}</p><h1>{service.name}<span>.</span></h1><h2>{service.subtitle}</h2><p>{service.intro}</p><Link className="site-button" to={`/rfq?process=${service.id}`}>Discuss this process <ArrowUpRight size={16} /></Link></div><PartPanel key={service.id} service={service} /></div><section className="service-facts site-width"><div><p className="eyebrow">WHERE IT FITS</p><h2>Applications</h2>{service.applications.map(a => <p className="application-line" key={a}><MoveUpRight size={16} />{a}</p>)}</div><div><p className="eyebrow">MATERIAL & DESIGN</p><h2>Start with the requirements.</h2><p>{service.materials}</p><p>{service.note}</p></div></section><section className="workflow-section"><div className="site-width"><SectionHeading label="THE PROCESS" title="From brief to component." /><div className="workflow-steps">{service.process.map((p, i) => <article key={p}><span>0{i + 1}</span><p>{p}</p></article>)}</div></div></section><section className="site-section site-width service-more"><h2>See the bigger picture.</h2><p>Explore this process in the context of an automotive assembly.</p><Link to="/#manufacturing" className="text-link">Open the 3D explorer <ArrowUpRight size={16} /></Link></section><ProjectCTA /></>;
}

export function AboutPage() { return <><PageIntro label="ABOUT AARPEE GROUP" title={<>Two disciplines.<br /><span>One shared ambition.</span></>} description="AARPEE Group brings AARPEE Industries and Thry Co together, connecting conventional manufacturing with additive possibilities." /><section className="about-editorial site-width"><div className="about-image"><img src="/manufacturing-hero.png" alt="Concept study of machined and printed component forms" loading="lazy" /><span>MACHINING + ADDITIVE MANUFACTURING</span></div><div><p className="eyebrow">OUR APPROACH</p><h2>Think beyond a single process.</h2><p>Some parts begin with a solid billet. Others emerge layer by layer. The right starting point depends on what the component needs to achieve.</p><p>AARPEE Industries focuses on VMC and billet machining, rubber components, jigs and fixtures. Thry Co opens another path through FDM, SLA and SLS printing.</p><p>Together, they make it easier to discuss a part from its early development through its manufacturing requirements.</p></div></section><section className="workflow-section"><div className="site-width"><SectionHeading label="WORKING TOGETHER" title="Clear thinking. Practical making." /><WorkflowSteps /></div></section><ProjectCTA /></>; }

export function SectorsPage() { return <><PageIntro label="APPLICATIONS & SECTORS" title={<>Different industries.<br /><span>Familiar challenges.</span></>} description="Fit, function, material and repeatability. Explore where our manufacturing capabilities can support your work." /><section className="sector-catalogue site-width">{sectors.map(s => <article key={s.name}><span className="sector-number">{s.number}</span><div><h2>{s.name}</h2><p>{s.description}</p><div className="process-tags">{s.services.map(id => <Link key={id} to={getService(id).path}>{getService(id).name}<ArrowUpRight size={12} /></Link>)}</div></div></article>)}</section><ProjectCTA /></>; }

export function ApplicationsPage() { return <><PageIntro label="THRY CO / APPLICATION GALLERY" title={<>Ideas you can<br /><span>put your hands on.</span></>} description="Illustrative component studies show how the printing process follows the purpose of the part." /><section className="application-gallery site-width">{services.filter(s => s.arm === 'thry').map(s => <article key={s.id}><PartPanel service={s} /><p className="eyebrow">{s.name}</p><h2>{s.part}</h2><p>{s.intro}</p><Link className="text-link" to={s.path}>Explore the process <ArrowUpRight size={15} /></Link></article>)}</section><ProjectCTA /></>; }

export function NotFoundPage() { return <section className="not-found site-width"><p className="eyebrow">404 / PAGE NOT FOUND</p><h1>A small detour.</h1><p>Let’s get you back to the right place.</p><Link to="/" className="site-button">Return home <ArrowRight size={16} /></Link></section>; }
